namespace Storporate.SharedKernel.Entities;

/// <summary>
/// One AI-derived skill finding for a <see cref="PortfolioItem"/>, written by STOR-38
/// Phase 2's background worker once an analysis job completes successfully. A successful
/// analysis replaces any prior findings for the item — there is no append-only history
/// here, just the latest snapshot of what the model thinks the evidence backs.
/// </summary>
/// <remarks>
/// <para>
/// <b>Schema-only POCO.</b> The mapping lives in
/// <c>Storporate.Infrastructure/Persistence/Configurations/PortfolioSkillFindingConfiguration.cs</c>,
/// following the standalone-configuration style established by <see cref="Job"/> and
/// <see cref="PortfolioItem"/>.
/// </para>
/// <para>
/// <b>Implements <see cref="IAccountScoped"/>.</b> Carries its own <see cref="AccountId"/>
/// rather than relying solely on the parent <see cref="PortfolioItem"/> because the EF Core
/// global query filter and the Postgres RLS policy both key on <c>AccountId</c> directly —
/// the filter expression is <c>e.AccountId == ambient || ambient.IsAdministrator</c>, with no
/// join. The Phase 2 worker writes the parent item's <see cref="PortfolioItem.AccountId"/>
/// onto every finding it inserts, so this column never diverges from the parent's.
/// </para>
/// <para>
/// <b>Free-form skill names.</b> STOR-30 deliberately defers skill-name standardization
/// across the platform until real data exists (see the STOR-38 plan, Constraints, "skill
/// names are free-form, generated by the AI per item"). The worker can therefore emit
/// near-duplicates across items ("React" vs. "React.js", "Public Speaking" vs.
/// "Public speaking") — reconciliation is a separate later story.
/// </para>
/// </remarks>
public sealed class PortfolioSkillFinding : IAccountScoped
{
    public Guid Id { get; set; }

    /// <summary>The owning <see cref="User.Id"/>. See class remarks.</summary>
    public Guid AccountId { get; set; }

    /// <summary>Navigation to the owning <see cref="User"/>. Not required at insert time —
    /// EF Core populates it from <see cref="AccountId"/> when the principal is loaded.</summary>
    public User? Account { get; set; }

    /// <summary>The <see cref="PortfolioItem.Id"/> this finding describes. Foreign-keyed with
    /// <see cref="Microsoft.EntityFrameworkCore.DeleteBehavior.Restrict"/> so deleting a
    /// portfolio item fails loudly while findings still exist (the Phase 2 worker is the
    /// path that removes findings — it does so before the item itself can be hard-deleted).</summary>
    public Guid PortfolioItemId { get; set; }

    /// <summary>Navigation back to the owning <see cref="PortfolioItem"/>. Populated by
    /// EF Core when the principal is loaded; not required at insert time.</summary>
    public PortfolioItem? PortfolioItem { get; set; }

    /// <summary>The free-form skill name the AI extracted from the evidence (e.g.
    /// "React", "Public Speaking", "Data Visualization"). See class remarks on
    /// standardization.</summary>
    public required string SkillName { get; set; }

    /// <summary>One of <see cref="ConfidenceBands"/>.</summary>
    public required string ConfidenceBand { get; set; }

    /// <summary>The model's short, evidence-grounded justification for the assigned
    /// <see cref="ConfidenceBand"/> — surfaced verbatim on the portfolio detail page so the
    /// student can audit *why* the model rated each skill the way it did.</summary>
    public required string Explanation { get; set; }

    public DateTimeOffset CreatedAt { get; set; }
}
